#!/usr/bin/env bash

before=$(git diff --name-only)

./idl/records_request_jsonschema.py | ./idl/jsonschema2klaxon.py informixcdc RecordsRequest > src/main/kotlin/informixcdc/RecordsRequest.kt

for file in $(git diff --cached --name-only | grep -e '\.kt$'); do
	ktlint --experimental -F "$file" &
done
wait

after=$(git diff --name-only)

changed=0
for file in $(diff <(echo "$before") <(echo "$after") | grep -e '\.kt$' | cut -b3-); do
	echo "Reformatted: $file"
	changed=1
done

exit "$changed"
